jenkins-infra/datadog

- plans/datadog-monitors.tf
This check spam us and is not really useful
> [INFRA-2239] Remove kubelet_ping_check monitoring check

- plans/datadog-monitors.tf
Not sure if there's a better way to do this, but this should stop me getting daily emails about it
I've edited it in the UI for now, just backporting to the code...
> Exclude evergreen and repo.azure

- plans/synthetics_get.tf
- plans/synthetics_pkg.tf
* Update pkg.jenkins.io monitoring to test pkg.origin
* Add get.jenkins.io synthetic test
> Add various syntetic tests

- plans/datadog-monitors.tf
Related to  https://github.com/jenkins-infra/docker-datadog/pull/9
Some cleanup may be needed in Datadog interface
Signed-off-by: Olivier Vernin <olivier@vernin.me>
> Remove plugin_site_index_age

- plans/datadog-monitors.tf
- plans/monitor-packages.tf
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> chore(terraform) fix deprecation syntax in datadog resources

- CODEOWNERS
Part of https://github.com/jenkins-infra/helpdesk/issues/2829
> chore: add "terraform" team to CODEOWNERS

- Jenkinsfile_k8s
- updatecli/updatecli.d/hashicorp-tools.yml
dockerimage as variable and correction of updatecli pattern
> chore: version of dockerimage in variable and then updatecli pattern correction

- updatecli/updatecli.d/hashicorp-tools.yml
- updatecli/updatecli.d/terraform-providers.yaml
… 
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> chore(updatecli) fix manifests - no more explicit version for datadog tf module + casing for 0.23.x

- synthetics_wiki.tf
as per issue https://github.com/jenkins-infra/helpdesk/issues/2907
trying synthetics probes
> chore(wiki): temporarily break a test to try datadog synthetics

- synthetics_wiki.tf
as per https://github.com/jenkins-infra/helpdesk/issues/2923
> fix(wiki): synthetic does not take http statusCode into account

- datadog-monitors.tf
- synthetics_issues.tf
- synthetics_wiki.tf
as following #78 this should correct error in header check.
> Correct 400 error

- synthetics_wiki.tf
> add a check on wiki.jenkins-ci.org

- synthetics_plugin-health-scoring.tf
Ref: https://github.com/jenkins-infra/helpdesk/issues/3114
cc @alecharp
> feat: add synthetic monitoring on plugin-health.jenkins.io

- datadog-monitors.tf
Warn when the available space on any persistent volume is below 20%, and alert if available space on any persistent volume is below 10%
Ref: https://github.com/jenkins-infra/helpdesk/issues/3425 & https://github.com/jenkins-infra/helpdesk/issues/2752
> feat: add volume available space monitoring

- datadog-monitors.tf
> fixup: exclude null for available disk space monitoring

- monitor-packages.tf
Would probably make sense to replace the infra room too, given that's where conversations happen atm, no? 🤔
> Replace jenkins-release with matrix room

- .terraform.lock.hcl
- synthetics_jenkinsio.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3753
> chore: migrate from tfsec to trivy

- synthetics_plugin-health-scoring.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3768
> add a monitoring of the plugin-health-scoring.jenkins.io probes

- synthetics_incrementals.tf
Ref: https://github.com/jenkins-infra/helpdesk/issues/3768
> feat: add synthetics test for `incrementals.jenkins.io`

- Jenkinsfile_k8s
- versions.tf
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1884960978
> feat(terraform) bump terraform cli version acceptance

- synthetics_updatecenter.tf
as per https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2335134108
we need to improve our test for the new updates.jenkins.io
> feat(updates): allow follow redirect to synthetics test for updates.jio

- synthetics_updatecenter.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
This PR creates a matrix of all URLs to check (from user point of view)
> feat(synt/updates.jenkins.io) create a matrix of URLs to check

- synthetics_updatecenter.tf
to catch any problem with redirections
> feat(synthetics_updatecenter) add /latest to monitoring

- synthetics_updatecenter.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
> feat(synthetics_updatecenter) add more endpoints to monitor

- synthetics_plugin-health-scoring.tf
Fix the `BODY_TOO_LARGE_TO_PROCESS: Error: Assertions processing the body/response cannot be run beyond 5242880b.` error
> fix(synthetics/PHS) do not parse heavy body - `BODY_TOO_LARGE_TO_PROCESS`

- synthetics_updatecenter.tf
For operation https://github.com/jenkins-infra/helpdesk/issues/4758
> feat(synthetics/updates.jio) disable update center monitoring

- synthetics_updatecenter.tf
Follow up of #309
Ref. https://github.com/jenkins-infra/helpdesk/issues/4758
> fix(synthetics_updatecenter) correct redirection location targets and enable pagerduty
