- Jenkinsfile
Obviously the .terraform directory is not moved between stages
> Run terraform init before each command

- plans/datadog-monitors.tf
Azure VM use by default a boot partition on /dev/sda15, which trigger datadog alert, I had to manually mute that checks but I think it safer to just disable monitoring for that partition, the probability that this partition is used for any others things than boot is pretty down to zero  
** EDIT **
I also reenable /dev/vda1 partition used by lettuce and radish, which for an unknown reason was explictiely not monitored
> Don't monitor /dev/sda15 which is used for boot partition on azure vm

- Jenkinsfile
This step is just a slower and there is no risk to remove it
> Remove review step

- docker/checks.d/packageCanBeDownloaded.py
It appears that moving the hostname variable to the class was a bad idea as it's  overriden  by Datadog check
> Fix packageCanBeDownloaded check 

- plans/monitor-packages.tf
This monitor was first tested on our Datadog account before being exported here.
The most important information is that we only trigger an alert if the latest packages haven't been available for at least 30min because at the moment it takes around 20min between the moment we do a maven release and the moment we build and publish distribution packages
Signed-off-by: Olivier Vernin <olivier@vernin.me>
> Monitor latest packages

- plans/datadog-monitors.tf
Only trigger alarms for Jenkins production services.
This change has only been applied manually via the UI as we got spam over the weekend for third mirrors instability.
Last Friday, we started monitoring third mirrors so we could have data when people report issues with get.jenkins.io. 
Signed-off-by: Olivier Vernin <olivier@vernin.me>
> Filter monitoring check for production services only

- plans/datadog-monitors.tf
It doesn't make sense to trigger disk space issues on those devices as they will always flag as 100% disk space used.
Signed-off-by: Olivier Vernin <olivier@vernin.me>
> Don't monitor loop device

- Jenkinsfile_k8s
- Makefile
- ci-pod-template.yml
- plans/.terraform.lock.hcl
- plans/main.tf
- updatecli/updatecli.d/ciPodTemplate.yml
- updatecli/values.yaml
This PR updates the repository to support Terraform 1.0.
It includes the following changes:
- Bump Datadog provider to [3.2.0](https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.2.0) (from [2.25](https://github.com/DataDog/terraform-provider-datadog/compare/v2.25.0...v3.2.0)) to avoid using deprecated or unavailable syntax from terraform <0.12
- Breaking: Update the `Makefile` to use the new Terraform 1.x CLI flag `-cli` used to change working directory.
* Because of this change, this PR requires https://github.com/jenkins-infra/docker-terraform/pull/49 to be merged and release (to be sure that Terraform 1.x is used with the CLI flag).
* That's why the terraform project had been constrained to the Terraform version 1.0.x
- Add a [terraform lock …
> breaking: bump terraform to 1.0.4 + all required dependencies

- plans/datadog-monitors.tf
The datadog monitor for the available free disk space triggers alerts when less than 1Gb is available.
For some machine, the UEFI boot device is triggering the alert because it's usually sized at 100Mb, even though it's 99% free.
This PR filters out these devices by disk label instead of device adress:
- Device adress can change on reboot (happened to ci.jenkins.io VM)
- UUID would be a pain to maintain
> fix(monitors:disk) exclude 'UEFI' and 'uefi' labels instead of named devices

- Jenkinsfile_k8s
- versions.tf
use of the hashicorp docker image that will use the new terraform 1.1.x instead of 1.0.x
as per https://github.com/jenkins-infra/shared-tools/issues/8
> feat: bump terraform to 1.1.x

- updatecli/scripts/terraform-get-upgraded-lockfile.sh
If the script fails it means updatecli has to be executed in the same environment as the rest of the pipeline to get the "current" terraform
Follow-up of https://github.com/jenkins-infra/datadog/pull/61
> fix: only test the presence of terraform in updatecli script

- synthetics_accountApp.tf
- synthetics_archives.tf
- synthetics_cijenkinsio.tf
- synthetics_issues.tf
- synthetics_javadoc.tf
- synthetics_jenkinsio.tf
- synthetics_mirrors.tf
- synthetics_pkg.tf
- synthetics_pluginsite.tf
- synthetics_repo_ui.tf
- synthetics_updatecenter.tf
- synthetics_uplink.tf
as per https://github.com/jenkins-infra/helpdesk/issues/2923
⚠️  This PR should be merged only just after a manual delete of the actual checks within datadog UI.
> fix: convert browser type to api

- synthetics_jenkinsio.tf
following https://github.com/jenkins-infra/datadog/pull/77 as it's now working we have alert on redirections 301.
> correct url for jenkins.io for 200

- datadog-monitors.tf
Ref: https://github.com/jenkins-infra/helpdesk/issues/2905
> cleanup: remove deprecated '@oncall' handles

- synthetics_mirrors.tf
to avoid the http to https redirection
> chore(https://mirrors.jenkins-ci.org): correcting http to https url

- synthetics_get.tf
- synthetics_mirrors.tf
- synthetics_wiki.tf
Why this change? https://github.com/jenkins-infra/datadog/pull/85#discussion_r883476033
The goal is to monitor the enforced HTTP to HTTPS redirection introduced by the actions in https://github.com/jenkins-infra/helpdesk/issues/2888 (consildating the DNS mirrors.jenkins* to the kubernetes-hosted mirrorbits service, same as get.jenkins.io).
> feat(mirrors,get) monitor http to https enforced redirection and use the same pattern for get and mirrors

- synthetics_accountapp_login.tf
- synthetics_artifact-caching-proxy-providers.tf
- variables.tf
I've put aside the `aws` provider as it's out of service right now.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3203 & https://github.com/jenkins-infra/helpdesk/issues/2752
> feat: add synthetic monitoring on artifact-caching-proxy providers

- variables.tf
The 'aws' artifact caching proxy is up now.
> chore: restore 'aws' artifact caching proxy provider

- synthetics_plugin-health-scoring.tf
Fixup of https://github.com/jenkins-infra/datadog/pull/128
> fixup: add missing scheme to plugin-health-scoring URL

- synthetics_plugin-health-scoring.tf
> fixup: plugin-health-scoring is returning a redirect at its root

- synthetics_artifact-caching-proxy-providers.tf
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/3537
> fix(artifact-caching-proxy): new `health` URL

- synthetics_jenkinsio.tf
- synthetics_pluginsite.tf
We've got frequent false alerts on these two website, this PR adds a retry which hopefully will resolve them.
> feat: retry twice before alerting on `plugins.jenkins.io` and `www.jenkins.io`

- datadog-monitors.tf
Instead of alerting when there is less than 1GB free space which can be too late for hosts with big disks, warn when the available disk space is below 20%, and alert when it's below 10%
Resolves https://github.com/jenkins-infra/helpdesk/issues/3497
> feat: switch to a percentage instead of an amount for available disk space monitor

- datadog-monitors.tf
This PR changes PagerDuty notifications to be sent only on alerts for monitorings with both alert and warning criteria
Fixes https://github.com/jenkins-infra/helpdesk/issues/3555
> chore: don't send PagerDuty notifications on warnings

- datadog-monitors.tf
The Jenkins DNS service doesn't exist anymore ("No data" in Datadog)
The link from this monitoring message points to a page that has been cleaned up in June 2022 cf https://github.com/jenkins-infra/runbooks/commit/eec5977 (private repository)
Ref: https://github.com/jenkins-infra/helpdesk/issues/3558
> chore: remove decommissioned `bind` service monitoring

- datadog-monitors.tf
- synthetics_jenkinsio.tf
Despite the `exclude_null()` correctly set, we saw warning on empty metrics which is weird.
While trying to understand these messages, we discovered the `system.disk.in_use` metric which is a fraction.
This PR utilizes this metric to simplify the disk monitor.
Tested manually and work as expected (only the `systempool` machines on `privatek8s` are in warn state)
Note: this PR includes 2 additional changes:
- In a separate commit: bump the `.shared-tools`. It wasn't working locally for me without this update, not sure why (haven't looked)
- A terraformt fmt recursive changed a line on an unrelated file. Insce it's only a blank line, I've added the change
> feat(disk monitor) utilizes the system.disk.in_use fraction to simplify formula and avoid false positives

- datadog-monitors.tf
We've recently been impacted by inodes full usage on infra.ci.jenkins.io, with this error in Jenkins logs:
> java.io.IOException: No space left on device
While space was left on the PV:
```
jenkins@jenkins-infra-0:/$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          97G   67G   30G  70% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda1        97G   67G   30G  70% /tmp
/dev/sdc         49G   32G   18G  66% /var/jenkins_home
shm              64M     0   64M   0% /dev/shm
tmpfs            13G  472K   13G   1% /run/secrets/additional
tmpfs            13G   12K   13G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.9G     0  7.9G   0% /proc/acpi
tmpfs           7.9G     0  7.9G   0% /proc/scsi
tmpfs …
```
> feat: add inodes monitoring

- datadog-monitors.tf
This monitor was in "no data", this PR fixes it by setting the correct monitoring type.
It also removes the `@all` notification in the message, superseded by `@pagerduty`, and removes the trailing slash at the end of the URL, not needed.
> fix: change the type of the `account_app_slow` monitor

- datadog-monitors.tf
This PR recreates as code an existing monitor which will then be manually deleted.
<details>
<summary>Export as JSON of the existing monitor:</summary>
```json
{
"id": 28992728,
"name": "Ldap process stopped",
"type": "process alert",
"query": "processes('ldap').over('command:slapd').rollup('count').last('5m') < 1",
"message": "Checked that the ldap container is running correctly by running \n```\nkubectl get pods -n ldap\n```\nAnd restart if necessary by running \n```\nkubectl delete pods -n ldap ldap-0\n``` @pagerduty",
"tags": [],
"options": {
"thresholds": {
"critical": 1
},
"renotify_interval": 0,
"notify_audit": false,
"timeout_h": 0,
"include_tags": true,
"no_data_timeframe": null,
"require_full_window": false,
"notify_no_data": false,
"escalation_message": "",
"silenced": {}
}, …
```
> chore: recreate as code the "LDAP process stopped" monitor

- datadog-monitors.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/3351, this PR exclude empty data AND data from `prodpublick8s` to avoid false alert now that the `datadog` namespace was removed from this cluster.
Tested manually and looks good!
> cleanup: ensure no more metrics from prodpublick8s are used for monitors

- synthetics_jenkinsio.tf
Messed up the staging in my previous PR hence the 302 > 301, and add the missing trailing slash in target location header.
Fixup of #195
> fixup: correct code and trailing `/` for `jenkins.io` redirections monitors

- datadog-monitors.tf
This PR adds a monitor on all Azure File Shares to warn when their volume usage is above 80% of their quota, and to alert if above 90%.
Current usage in percent:
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3924
> feat: add a monitor on Azure File Shares volume usage

- synthetics_incrementals.tf
This PR improves incrementals.jenkins.io synthetics monitor by watching the `/readiness` endpoint returning a 200 status code instead of `/` returning a 404 status code.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3933
> fix(incrementals): use `/readiness` endpoint returning a 200 status code

- synthetics_plugin-health-scoring.tf
This PR adds a monitor to ensure PHS report isn't empty and contains at least "lastUpdate".
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4056#issuecomment-2091045391
> feat(plugin-health-scoring): add a monitor on the report content

- datadog-monitors.tf
- synthetics_incrementals.tf
- variables.tf
As per https://github.com/jenkins-infra/helpdesk/issues/3954\#issuecomment-2119858778
This PR introduces 2 changes on the datadog monitor to avoid triggering alerts following the clusters removals:
- Remove `repo.aws` and `repo.do` ACP monitors
- Ensure that the HTTP response time are only checked through the `publick8s` (as doks-public is removed)
> cleanup: remove monitors referencing removed clusters `cik8s`, `eks-public`, `doks` and `doks-public` and their hosted services

- synthetics_statsjenkinsio.tf
This PR adds monitoring for docs.jenkins.io
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2167717401
> feat: add `stats.jenkins.io` synthetics monitoring

- Jenkinsfile_k8s
Related to https://github.com/jenkins-infra/helpdesk/issues/4167, this PR introduces the following changes to the pipeline:
- Staging is now really using staging (distinct API key than production and read-only-scoped application key)
- Update production credential IDs
Note: had to run a `rm -rf ./.terraform && make -C .shared-tools/terraform/ validate` with both new `production` and `staging` backends to ensure the remote states are fully up to date.
> chore: set up pipeline to use the new staging backend

- imports.tf
- logs_pipeline.tf
In order to work on the "parse Nginx Ingress logs"  (ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2335134108), we need to import the existing "manually-defined" pipeline parsers as a prerequisite.
- This imports the resources along defining them
-  A subsequent PR is expected to remove the `imports.tf` file afterwards
- We expect a few updates in the existing objects:
- Filters have a trailing space which is removed by this PR during import
- Some API changes are marked as "change". We tried one manually (and then reverted it) so it should be good. As a matter of safety, I've backed up locally the existing pipelines
- As explained in the added comment: we can (and should) use the Datadog UI for customizing (using the samples) the parsers. But we **must** add …
> feat: define and import logs pipelines (integrations, custom pipelines and the whole ordering)

- logs_pipeline.tf
Following https://github.com/jenkins-infra/helpdesk/issues/4372 (in the context of https://github.com/jenkins-infra/helpdesk/issues/2649), we had to update the Logs Pipeline to properly parse the access logs pushed by Cloudflare to datadog.
The default integration was enabled automatically after we started to push logs to datadog, but it targets the `source` set to `cloudflare` while we set it up to be `cloudlfare-r2`.
This PR is a first step to import the configuration we did manually in Datadog UI:
- Disabled the default integration (for now?)
- Duplicated it so we could set the `source` filter to the value we need.
Notes:
- This PR expects 2 imports and no changes as tested locally
- We need a subsequent PR with `updatecli` to retrieve the source value from the Terraform Cloudflare …
> feat(logs_pipeline) define and import the Cloudflare Logs pipelines

- imports.tf
- logs_pipeline.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649
> fix(logs_pipeline) parse all kind of mirrorbits message with the proper attributes and log_level to stop pushing false-positive `ERROR` messages

- synthetics_plugin-health-scoring.tf
Ref. https://github.com/jenkins-infra/kubernetes-management/pull/6509#issuecomment-2834704350
PHS provides a really useful health endpoint: https://plugin-health.jenkins.io/actuator/health
```json
{"status":"UP","groups":["liveness","readiness"]}
```
Note: tested manually with success:
> feat(synthetics/PHS) use the correct health probe

- logs_pipeline.tf
- synthetics_plugin-health-scoring.tf
A new pipeline log aggregator has been added by Datadog in their UI, making the Terraform job shifting.
This PR imports this new pipeline, `openvpn`
> feat(logs_pipeline) import the new 'openvpn' log pipeline

- synthetics_updatecenter.tf
The datadog synthetics fails quite often on the update center with the error `NGHTTP2_REFUSED_STREAM`:
This PR introduces 2 changes in these synthetics to ensure we don't get that much positives while keeping the monitoring:
- Many locations (2 different clouds, 2 continents and 3 geographical zones) to ponder errors (in case it comes from datadog infrastructure)
- Retry 3 times the requests before triggering the monitor
> fix(synthetics/updatecenter) attempt to decrease false positive alerts
